### ISSUE TITLE
error

### ISSUE THREAD

**Issue by abhatt1250** [twitter/hbc#122]
i have been trying to run my hbc but i get the following error .

[com.twitter.hbc.example.SampleStreamExample.main()] INFO com.twitter.hbc.httpclient.BasicClient - New connection executed: sampleExampleClient, endpoint: /1.1/statuses/sample.json?delimited=length&stall_warnings=true
[hosebird-client-io-thread-0] INFO com.twitter.hbc.httpclient.ClientBase - sampleExampleClient Establishing a connection
[hosebird-client-io-thread-0] WARN com.twitter.hbc.httpclient.ClientBase - sampleExampleClient IOException caught when establishing connection to https://stream.twitter.com/1.1/statuses/sample.json?delimited=length&stall_warnings=true
[hosebird-client-io-thread-0] WARN com.twitter.hbc.httpclient.ClientBase - sampleExampleClient failed to establish connection properly
[hosebird-client-io-thread-0] INFO com.twitter.hbc.httpclient.ClientBase - sampleExampleClient Done processing, preparing to close connection

plzz help

**Comment by andypiper** [comment]
Closing out old issues.
