### ISSUE TITLE
Problem with Apache HTTP client

### ISSUE THREAD

**Issue by shenghuang** [twitter/hbc#131]
I got the following error after importing Twitter HBC libraries into my Android project:
java.lang.NoClassDefFoundError: org.apache.http.impl.conn.SchemeRegistryFactory
            at com.twitter.hbc.ClientBuilder.<init>(ClientBuilder.java:102)

Some Internet threads say the Apache HTTP client library collides with the Android built-in one, thus I added the following library dependency following https://hc.apache.org/httpcomponents-client-4.3.x/android-port.html
    compile group: 'org.apache.httpcomponents' , name: 'httpclient-android' , version: '4.3.5'

This doesn't work as well. Now it complains some other errors. Another library
http://code.google.com/p/httpclientandroidlib/ says it could work, but it requires to import ch.boye.httpclientandroidlib.\* instead of org.apache.http.*. 

It seems that org.apache.http.conn.scheme.SchemeRegistry is imported in https://github.com/twitter/hbc/blob/master/hbc-core/src/main/java/com/twitter/hbc/ClientBuilder.java, so I don't think it is a good idea to change the ClientBuilder class to change the import statement.

Is there a solution? How can make the Twitter streaming work? Thanks in advance.

**Comment by lgorse** [comment]
I also hit this problem. I'm assuming there's a really simple solution since this is a Twitter-supported project - and all it takes is someone to respond to this thread?

**Comment by Eugenijus** [comment]
I have the same issue when trying to use hbc-core in android development (Android Studio). I get:
java.lang.NoClassDefFoundError: org.apache.http.impl.conn.SchemeRegistryFactory

In my gradle dependencies I added these lines:
compile 'org.apache.httpcomponents:httpclient:4.2.5'
compile 'com.twitter:hbc-core:2.2.0'

But when I open ClientBuilder.java the following import still cannot be found:
import org.apache.http.impl.conn.SchemeRegistryFactory;

I tried httpclient 4.4.1 as well. My App is targeted for minSdkVersion 17 and targetSdkVersion 21.

This is very cool project/library and it would be awesome if it worked on Android as well.

**Comment by hamen** [comment]
Same issue here:

```java
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/impl/conn/SchemeRegistryFactory;
            at com.twitter.hbc.ClientBuilder.<init>(ClientBuilder.java:102)
```

Any possible solution?

**Comment by emptyflash** [comment]
Also hitting this issue. As far as I can tell, android uses an older version of `org.apache.httpcomponents:httpclient`. Which was the conclusion of [this google group discussion](https://groups.google.com/forum/#!topic/ektorp-discuss/hZygPBSNkNE), and [this StackOverflow answer](http://stackoverflow.com/questions/16631784/can-i-use-a-new-version-of-httpclient-in-my-android-project) offers a solution to use a port of a newer version of HttpComponents. Apache actually has it own [official port for Android](https://hc.apache.org/httpcomponents-client-4.3.x/android-port.html).

So it looks like it might be necessary to have a fork of this project that uses Apache's HttpComponents for Android.

**Comment by emptyflash** [comment]
Okay, if anyone also hitting this problem wants to give this solution a whirl: here's a repo you can use: https://jitpack.io/#emptyflash/hbc/hbc-2.2.0

Let me know if it works, I'm having difficulty getting it to work in my project right now, but I think it's more of a build issue.
