### ISSUE TITLE
Correct way for reconnection of client..

### ISSUE THREAD

**Issue by alex-in2** [twitter/hbc#134]
Consider scenario..
From time to time my filter criteria changed and I need to add or remove tags from StatusesFilterEndpoint. I tried to implement it with closing old client, change criteria and connect again.
In some cases (quite easy) when I connect again I have "status code - 420, reason - Enhance Your Calm" error, It seems that I step out for some limit. What is the correct way to reconnect and apply new filter criteria ?

**Comment by huysamen** [comment]
This would also be useful to us.  Have you made any progress with this?

**Comment by jayv** [comment]
It's a client issue. Connections with very few or no matches to filter criteria wait on a match to come to a stop, so they stay open in the background thread even though the shutdowns method returns due to timeout. In this scenario you get the 420 when making a new connection.
