### ISSUE TITLE
Twitter4j BlockingQueue.queue gives nullpointer exception when used with axis 2 jars

### ISSUE THREAD

**Issue by riteshkapadia** [twitter/hbc#139]
I am trying to use the twitter4j API for consuming the streaming API for twitter. It is working perfecting fine until i have added few axis 2 libraries.

Code:

    BlockingQueue<String> queue = twitter.getBlockingQueue();
        //Infinite loop to always receive the messages
        while (true) {
            String twitterServerReply = null;
            try{
                twitterServerReply = queue.take();
            }
            catch(Exception e){
                e.printStackTrace();
            }}     

Following is the exception i am getting:

    Exception in thread "hosebird-client-io-thread-0" java.lang.NullPointerException
	at com.twitter.hbc.httpclient.RestartableHttpClient.getConnectionManager(RestartableHttpClient.java:83)
	at com.twitter.hbc.httpclient.ClientBase.run(ClientBase.java:165)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)    
  
my POM.xml:

    <modelVersion>4.0.0</modelVersion>
	<groupId>com.twitter</groupId>
	<artifactId>hbc-example</artifactId>
	<version>2.2.1-SNAPSHOT</version>
	<packaging>jar</packaging>
	<name>Hosebird Client Examples</name>
	<dependencies>
		<dependency>
			<groupId>com.twitter</groupId>
			<artifactId>hbc-core</artifactId> 
			<version>2.2.0</version> 
		</dependency>
		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>
			<version>1.1.1</version>
		</dependency>
		<dependency>
			<groupId>org.twitter4j</groupId>
			<artifactId>twitter4j-core</artifactId>
			<version>[4.0,)</version>
		</dependency>
		 <dependency>
			<groupId>org.apache.axis2</groupId>
			<artifactId>axis2</artifactId>
			<version>1.6.2</version>
		</dependency>
		<dependency>
			<groupId>org.apache.axis2</groupId>
			<artifactId>axis2-adb</artifactId>
			<version>1.6.2</version>
		</dependency>
		<dependency>
			<groupId>org.apache.axis2</groupId>
			<artifactId>axis2-transport-local</artifactId>
			<version>1.6.2</version>
		</dependency><dependency>
			<groupId>org.apache.axis2</groupId>
			<artifactId>axis2-kernel</artifactId>
			<version>1.6.2</version>
		</dependency>
		<dependency>
			<groupId>org.apache.axis2</groupId>
			<artifactId>axis2-transport-http</artifactId>
			<version>1.6.2</version>
		</dependency>
	</dependencies>
</project>    
  

I  have to use AXIS 2 as i need to consume some SOAP webservices. Can anyone please help-out to check if with which dependencies i might be getting the issue?

NOTE: It works perfectly fine if i remove all the axis 2 dependency.

**Comment by richmidwinter** [comment]
I've run into this with hadoop too. Think it was an Apache HttpClient dependency conflict.
