### ISSUE TITLE
twitter streaming stopped working

### ISSUE THREAD

**Issue by macinux** [twitter/hbc#143]
The twitter streaming api stopped working since last night. The log shows

 New connection executed: hosebird-client-0, endpoint: /1.1/statuses/filter.json?delimited=length&stall_warnings=true
01/14 18:00:38 INFO [hosebird-client-io-thread-0] c.t.h.h.ClientBase - hosebird-client-0 Establishing a connection
01/14 18:00:39 WARN [hosebird-client-io-thread-0] c.t.h.h.ClientBase - hosebird-client-0 Error connecting w/ status code - 401, reason - Authorization Required

Can you let me know what causing this issue. It had bee working for more than a year. Thanks.

**Comment by macinux** [comment]
btw, curl still works. but not from  your library.  Please help me out since our production is down. thanks!!!

**Comment by macinux** [comment]
I think it is related to set the filter level to Medium. it works again after we remove this.

**Comment by macinux** [comment]
we still have this issue.  no data received if we set the filter level to medium. data received if we don't set it.  We really need the filter level to be medium to avoid the onTrackLimitationNotice. Thanks.

**Comment by tmcf** [comment]
Hi,
We recently had the same issue, but it was time drift on one of our servers causing the oauth to be rejected as its creation time was too far off.

vandannguyen gives a very good explanation of the issue here:
https://vandannguyen.wordpress.com/2014/12/02/twitter-error-connecting-w-status-code-401-reason-authorization-required/

**Comment by mgalushka** [comment]
@tmcf I have exactly the same issue, but it is related neither to incorrect time on my machine nor to filter level (I don't set it at all), please, help to understand why API suddenly stoppe working.
