### ISSUE TITLE
How (if it's possible) to track rate limit and determine the delay before reconnecting the client?

### ISSUE THREAD

**Issue by jk171505** [twitter/hbc#147]
I want to update endpoint's trackTerms. How can I determine an appropriate delay before reconnecting the client to avoid 420 response?

**Comment by cristobal-wetzig** [comment]
I'm also curious about this. I want to be able to catch 420 status for other purposes.

PS.

Have you looked into the ReconnectionManager interface that is implemented in the BasicReconnectionManager?

**Comment by cristobal-wetzig** [comment]
I ment handleconnection.... https://github.com/twitter/hbc/blob/ac4cbdf561961fba9c6ea655c5f334cce4f7d5a9/hbc-core/src/main/java/com/twitter/hbc/httpclient/ClientBase.java#L198

**Comment by dmitriy-svds** [comment]
+1

**Comment by jayv** [comment]
You may be running into https://github.com/twitter/hbc/issues/141
