### ISSUE TITLE
Changes required to adapt the new REST changes for DM increased to more than 140 Characters.

### ISSUE THREAD

**Issue by riteshkapadia** [twitter/hbc#152]
Hi Team,

As the twitter is changing the REST API to adapt the more than 140 characters in DM change, will this impact the projects using hbc?

If it is a major impact, what steps should we take to adapt it. Also, are we planing a next release to adapt this changes to support more than 140 character limit.

Thanks.

**Comment by riteshkapadia** [comment]
Any updates on this please?

**Comment by andypiper** [comment]
No changes are required here to handle longer Tweets.
