### ISSUE TITLE
API Homogeneity

### ISSUE THREAD

**Issue by RobertBakic** [twitter/hbc#157]
Constructors for objects Twitter4jSitestreamClient and  Twitter4jUserstreamClient should accept :

```
List<? extends SiteStreamsListener> listeners
```

and 

```
List<? extends UserStreamListener> listeners 
```

respectively, like  Twitter4jStatusClient does with : 

```
List<? extends StatusListener> listeners
```

**Comment by andypiper** [comment]
Site Streams and User Streams have now been retired so this issue is redundant.
