### ISSUE TITLE
dataStream connection protocol

### ISSUE THREAD

**Issue by powerofviva** [twitter/hbc#161]
Hello, 
I am trying to do research about stream protocol , i interested in  hbc , would you please let me know how to made connection to the twitter API , i am interesting to know about the protocol that has beed used . WebSocket , Rest , Http ..?  
it is appreciated to let me have access to source code in connection part . 

thanks in advance

**Comment by Rexhaif** [comment]
Try to read about http keep-alive connections and http streaming.

**Comment by powerofviva** [comment]
so it is using http1.1 with keepalive in header ?
