### ISSUE TITLE
Backfill in PT2.0 is not supported.

### ISSUE THREAD

**Issue by ghost** [twitter/hbc#171]
Hi,
Earlier for backfill in PT1.0 we need to pass clientId to get last 5 mins of backfill data. Now in documentation it is mentioned that we need to pass **backfillMinutes** variable. Can you please add in hbc-module so that we can pass the backfillMinutes as parameter. 

Thanks in advance
Amit

**Comment by rjdean123** [comment]
taking a look at this.

to other contributors--feel free to reach out as I'm new to this project and would love to say hi. didnt see an IRC or anything.
