### ISSUE TITLE
Fix BasicAuth when using PowerTrack 2.0

### ISSUE THREAD

**Issue by boosh** [twitter/hbc#173]
This looks like it should work, but I get a 401 "Authorization Required" response when I use it with PowerTrack 2.0:

```
val auth = new BasicAuth(username, password)
val client = new ClientBuilder()
  .name("GnipClient")
  .hosts("https://gnip-stream.twitter.com")
  .endpoint(endpoint)
  .authentication(auth)
  .processor(new LineStringProcessor(queue))
  .gzipEnabled(true)
  .build()
```

Debugging shows no auth header is sent with the request:

> DEBUG [org.apache.http.impl.conn.DefaultClientConnectionOperator] Connecting to gnip-stream.twitter.com:443
> DEBUG [org.apache.http.client.protocol.RequestAddCookies] CookieSpec selected: best-match
> DEBUG [org.apache.http.client.protocol.RequestAuthCache] Auth cache not set in the context
> DEBUG [org.apache.http.client.protocol.RequestTargetAuthentication] Target auth state: UNCHALLENGED
> DEBUG [org.apache.http.client.protocol.RequestProxyAuthentication] Proxy auth state: UNCHALLENGED
> DEBUG [org.apache.http.impl.client.DefaultHttpClient] Attempt 1 to execute request
> DEBUG [org.apache.http.impl.conn.DefaultClientConnection] Sending request: GET /stream/powertrack/accounts/MY_ACC/publishers/twitter/prod.json HTTP/1.1
> DEBUG [org.apache.http.wire] >> "GET /stream/powertrack/accounts/MY_ACC/publishers/twitter/prod.json HTTP/1.1[\r][\n]"
> DEBUG [org.apache.http.wire] >> "Accept-Encoding: gzip,deflate[\r][\n]"
> DEBUG [org.apache.http.wire] >> "Host: gnip-stream.twitter.com[\r][\n]"
> DEBUG [org.apache.http.wire] >> "Connection: Keep-Alive[\r][\n]"
> DEBUG [org.apache.http.wire] >> "User-Agent: Hosebird-Client 2.2.0[\r][\n]"
> DEBUG [org.apache.http.wire] >> "[\r][\n]"
> DEBUG [org.apache.http.headers] >> GET /stream/powertrack/accounts/MY_ACC/publishers/twitter/prod.json HTTP/1.1
> DEBUG [org.apache.http.headers] >> Accept-Encoding: gzip,deflate
> DEBUG [org.apache.http.headers] >> Host: gnip-stream.twitter.com
> DEBUG [org.apache.http.headers] >> Connection: Keep-Alive
> DEBUG [org.apache.http.headers] >> User-Agent: Hosebird-Client 2.2.0
> DEBUG [org.apache.http.wire] << "HTTP/1.1 401 Authorization Required[\r][\n]"
> DEBUG [org.apache.http.wire] << "connection: close[\r][\n]"
> DEBUG [org.apache.http.wire] << "content-length: 138[\r][\n]"
> DEBUG [org.apache.http.wire] << "content-type: application/json; charset=utf-8[\r][\n]"
> DEBUG [org.apache.http.wire] << "date: Tue, 19 Jul 2016 14:18:21 GMT[\r][\n]"
> DEBUG [org.apache.http.wire] << "server: tsa[\r][\n]"
> DEBUG [org.apache.http.wire] << "x-connection-hash: 2473a62afd5d8bf2163f1e3259091fb1[\r][\n]"
> DEBUG [org.apache.http.wire] << "[\r][\n]"

**Comment by boosh** [comment]
I don't have time to open a PR, but I'm using this replacement for `BasicAuth` instead which works:

```
package com.twitter.hbc.httpclient.auth;

import com.google.common.base.Preconditions;
import org.apache.http.HttpHeaders;
import org.apache.http.auth.AuthScope;
import org.apache.http.auth.UsernamePasswordCredentials;
import org.apache.http.client.methods.HttpUriRequest;
import org.apache.http.impl.client.AbstractHttpClient;
import sun.misc.BASE64Encoder;

/**
 * Reimplementation of BasicAuth that actually works.
 */
public class WorkingBasicAuth implements Authentication {
    private final String username, password;

    public WorkingBasicAuth(String username, String password) {
        this.username = Preconditions.checkNotNull(username);
        this.password = Preconditions.checkNotNull(password);
    }

    public void setupConnection(AbstractHttpClient client) {
        client.getCredentialsProvider().setCredentials(
                AuthScope.ANY,
                new UsernamePasswordCredentials(username, password)
        );
    }

    @Override
    public void signRequest(HttpUriRequest request, String postParams) {
        request.setHeader(HttpHeaders.AUTHORIZATION,
                createAuthHeader(this.username, this.password));
    }

    private String createAuthHeader(String username, String password) {
        BASE64Encoder encoder = new BASE64Encoder();
        String authToken = username + ":" + password;
        return "Basic " + encoder.encode(authToken.getBytes());
    }
}

```

**Comment by saikamineni** [comment]
@boosh  Did you get "IOException caught when establishing connection to https://gnip-stream.twitter.com/stream/PRODUCT/accounts/ACCOUNT_NAME/publishers/twitter/STREAM.json " warning while connecting to PowerTrack-2.0

The IOException says "org.apache.http.conn.HttpHostConnectException: Connection to http://gnip-stream.twitter.com refused" in my case.

**Comment by boosh** [comment]
@saikamineni I don't think so. I ended up copying `EnterpriseStreamingEndpoint` and updating the URLs in it to reflect the powertrack 2.0 URLs.

I got it working in the end...

**Comment by saikamineni** [comment]
I am trying to get https://github.com/gnip/sample-kinesis-connector working for PowerTrack 2.0 . But the connection isn't establishing. But the connection is established when I tried using EnterpriseStreamExample.

**Comment by boosh** [comment]
`EnterpriseStreamingEndpoint` uses the wrong URL. Copy it and create your own version replacing BASE_PATH with:
```
private static final String BASE_PATH = "/stream/powertrack/accounts/%s/publishers/%s/%s.json";
```
Worked for me.

**Comment by saikamineni** [comment]
Yes, I made all the changes to point to the new URL and tested with EnterpriseStreamExample, I was able to pull the data. Once I start integrating it with Sample Kinesis Connector the connection is not being established.

![image](https://cloud.githubusercontent.com/assets/7270619/17254752/bb58db40-55d3-11e6-884b-a3128e5a831a.png)

This is the stacktrace of the exception.

**Comment by boosh** [comment]
Not sure. Those http:// protocols should be https:// though I guess.

**Comment by rj93** [comment]
I had the same issue. I created a pull request here: https://github.com/twitter/hbc/pull/169

**Comment by bobber205** [comment]
@saikamineni Did you ever figure out your issue? I'm having the same issue! <3

**Comment by saikamineni** [comment]
If you are try to get this working for PowerTrack 2.0, check the dependencies. One of the dependencies related to AWS caused the issue in my case.

**Comment by roblovelock** [comment]
If you are using HBC to connect to PowerTrack 2.0 using the same method in pull request #169 by @rj93 then a recent change to the twitter API will cause your connection to fail authorisation. 

The reason is that `auth.signRequest` is called multiple times in `com.twitter.hbc.httpclient.ClientBase` and multiple headers are added to the request. A simple workaround is to check in the `signRequest` method and only add a header if it doesn't exist...
```
if(request.getFirstHeader("Authorization") == null) {
    request.addHeader("Authorization", authValue);
}
```
