### ISSUE TITLE
Broken link on README

### ISSUE THREAD

**Issue by mfirry** [twitter/hbc#183]
First line of `README.md` still links to [Streaming API](https://developer.twitter.com/docs/streaming-apis) which has moved somewhere else.

**Comment by TheSwaggomat** [comment]
Is this the correct link? https://developer.twitter.com/en/docs/tweets/filter-realtime/overview

**Comment by TheSwaggomat** [comment]
This link is also not working [control stream support for sitestreams](https://dev.twitter.com/docs/streaming-apis/streams/site/control).
