### ISSUE TITLE
Create release with support for powertrack 2

### ISSUE THREAD

**Issue by nilsga** [twitter/hbc#184]
As described here: http://support.gnip.com/articles/updating-hbc-for-ptv2.html

The code seems to be available, so hopefully, all there is to do is merge and create a new release.

**Comment by nilsga** [comment]
Seems like there alredy is a PR ready, too: https://github.com/twitter/hbc/pull/175

**Comment by bobber205** [comment]
I was told by our Twitter Rep this project is no longer maintained. RIP. 

Last year when I was going through the transition I tried the branch in #175  -- it didn't work.

I was able to make this work pretty easily https://github.com/gnip/sample-ruby-connector

**Comment by nilsga** [comment]
To be honest, I suspected it was... Maybe someone should officially state it though. Thanks for the link to the connector. Will have a look at it.

**Comment by bobber205** [comment]
FWIW You'll wanna check for heartbeats manually and reconnect -- They've recently let connections drop in a weird way and the only way to know if to check for heartbeats

**Comment by andypiper** [comment]
Working on merging the PowerTrack 2.0 support.
