### ISSUE TITLE
Proxy in ClientBuilder

### ISSUE THREAD

**Issue by yangmeijian** [twitter/hbc#196]
Hi, I am trying to use the proxy method in ClientBuilder according to the new source code, but the IDE says it cannot resolve method 'proxy'. My code as below and would be appreciated for any input.

```
        ClientBuilder builder= new ClientBuilder()
                .name("Hosebird-Client-01")
                .proxy(proxyHost,proxyPort)//'proxy' is in red
                .hosts(hosebirdHosts)
                .authentication(hosebirdAuth)
                .endpoint(hosebirdEndpoint)
                .processor(new StringDelimitedProcessor(msgQueue));
```

**Comment by velram** [comment]
Hi @yangmeijian & @azdravkovski - I'm also facing the same issue. Is there any solution that you guys have found out?
