### ISSUE TITLE
How do I get token and secret

### ISSUE THREAD

**Issue by learnconcept** [twitter/hbc#208]
hi Team,

I have created twitter developer tool to read the feeds. I see in the sample code as below
Authentication hosebirdAuth = new OAuth1("consumerKey", "consumerSecret",token, secret);

but in the tool its generated 
1. API Key
2. API Key Secret
3. Bearer Token

how do I get token and secret from BearerToken so that I can create Authentication object?
Please help I got stuck here

**Comment by hainna01** [comment]
@learnconcept did you ever get to the bottom of this? Im in the same spot and similarly confused.

**Comment by learnconcept** [comment]
@hainna01 
Yes its my bad I have not scrolled down of the page. Sorry, closing this issue.
