### ISSUE TITLE
Call to client.connect() fails: java.lang.NullPointerException

### ISSUE THREAD

**Issue by jarandaf** [twitter/hbc#47]
Hi there,

I'm trying to use the client without much success. I had a look at the examples and wrote my own classes but I can't avoid this annoying issue: every time I call the connect method from the BasicClient class I'm getting this exception (it does not matter whether I use directly the BasicClient or I try to wrap it into the Twitter4jStatusClient class):

<code>
Exception in thread "hosebird-client-io-thread-0" java.lang.NullPointerException
    at com.twitter.hbc.httpclient.RestartableHttpClient.getConnectionManager(RestartableHttpClient.java:89)
    at com.twitter.hbc.httpclient.ClientBase.run(ClientBase.java:165)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
</code>

Actually, by simply copying some code example from the hbc-example module (e.g.: SampleStreamExample) the error is still there. Running the same code from the hbc-module gives no error and works properly; I am definetely missing something...

I ran the debugger and the error is caused by the underlying property from the ClientBase class, which when executing line 165 from this class, is null.

The complete stack is:

<code>
Daemon Thread [hosebird-client-io-thread-0](Suspended %28exception NullPointerException%29)  
    RestartableHttpClient.getConnectionManager() line: 89  
    ClientBase.run() line: 165  
    ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) line: 1145  
    ThreadPoolExecutor$Worker.run() line: 615  
    Thread.run() line: 722  
</code>

Any help will be much appreciated, thanks.

**Comment by richmidwinter** [comment]
I had this issue with hadoop dependencies also pulling in (different) versions of httpclient.
